fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff check
        entry: poetry run ruff check
        args: [--fix]
        language: system
        types: [file, python]

      - id: ruff-format
        name: Ruff format
        entry: poetry run ruff format
        language: system
        types: [file, python]
