site_name: "Fusion Conventions: Standard Names"
site_url:
  !ENV [SITE_URL, "https://iterorganization.github.io/IMAS-Standard-Names/"]

plugins:
  - macros:
      verbose: true
  - data:
      sources:
        standardnames: !ENV [STANDARD_NAMES_FILE, standardnames.yml]
  - search
  - table-reader
  - mike:
      canonical_version: latest
      version_selector: true
      css_dir: stylesheets
      javascript_dir: javascripts

watch:
  - !ENV [STANDARD_NAMES_FILE, standardnames.yml]

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top

extra:
  version:
    provider: mike

# Enable latex/math notation
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - footnotes

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
