site_name: "Fusion Conventions: Standard Names"
plugins:
  - macros
  - data:
      sources:
        standardnames: standardnames.yml
  - search
  - table-reader
watch:
  - standardnames.yml
theme:
  name: material

# Enable latex/math notation
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - footnotes

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js