site_name: "Fusion Conventions: Standard Names"
site_url:
  !ENV [SITE_URL, "https://iterorganization.github.io/IMAS-Standard-Names/"]

plugins:
  - macros:
      verbose: true 
  - data:
      sources:
        standardnames: !ENV [STANDARD_NAMES_FILE, standardnames.yml]
  - search
  - table-reader

watch:
  - !ENV [STANDARD_NAMES_FILE, standardnames.yml]

theme:
  name: material

# Enable latex/math notation
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - footnotes

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
