name: Install imas-standard-names project
description: Manage a cached Poetry environments for testing and documentation.

inputs:
  python-version:
    description: "Python version to set up."
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Install poetry
      shell: bash
      run: pipx install poetry
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: "poetry"
    - name: Install dependencies
      shell: bash
      run: poetry sync --all-extras
