name: Install imas-standard-names project
description: Manage a cached Poetry environments for testing and documentation.

inputs:
  python-version:
    description: "Python version to set up."
    required: true

runs:
  using: "composite"
  steps:
    - name: Install poetry
      shell: bash
      run: pipx install poetry

    - uses: actions/setup-python@v5
      id: setup-python
      with:
        python-version: ${{ inputs.python-version }}
        cache: "poetry"

    - name: Re-sync dependencies when cache is not hit
      if: ${{ steps.setup-python.outputs.cache-hit != 'true' }}
      shell: bash
      run: poetry sync --all-extras --without dev
