name: Install imas-standard-names project
description: Manage a cached Python environment for testing and documentation.
      
inputs:
  python-version:
    description: "Python version to set up."
    required: true
  pip-extras:
    description: "Optional extras to pass to pip install (e.g. 'test,docs')"
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ inputs.python-version }}-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ inputs.python-version }}-
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        if [ -n "${{ inputs.pip-extras }}" ]; then
          python -m pip install .[${{ inputs.pip-extras }}]
        else
          python -m pip install .
        fi
