name: Build documentation
description: Build documentation detailing additions to the standardnames.yml file.

inputs:
  doc-ref:
    description: "Documentation name."
    required: true
  standard-names-file:
    description: "Name for the Standard Names documentation file."
    required: false
    default: "submission.yml"
  single-page:
    description: "Generate a single page documentation."
    required: false
    default: "true"

outputs:
  doc-ref:
    description: "Documentation name."
    value: ${{ inputs.doc-ref }}

runs:
  using: "composite"
  steps:

    - name: Prune docs directory 
      if: ${{ inputs.single-page == 'true' }}
      shell: bash
      run: find docs -name "*.md" ! -name "index.md" -type f -delete
  
    - name: Build documentation
      env:
        SITE_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ inputs.doc-ref }}
        STANDARD_NAMES_FILE: ${{ inputs.standard-names-file }}
      shell: bash
      run: |
        git fetch origin gh-pages --depth=1
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
        poetry run mike deploy "${{ inputs.doc-ref }}" --deploy-prefix issues --push --allow-empty
