name: Parse Issue
description: Parse Standard Name issue body and extract submission data.

inputs:
  template_path:
    description: "Path to the issue template."
    required: true
    default: ".github/ISSUE_TEMPLATE/standard-name.yml"

outputs:
  standard-name:
    description: "Proposed Standard Name."
    value: ${{ steps.issue-data.outputs.standard_name }}
  issue-number:
    description: "The issue number."
    value: ${{ steps.issue-info.outputs.issue_number }}
  ready-to-commit:
    description: "A boolean flag indicating if the proposal is ready to commit."
    value: ${{ steps.issue-data.outputs.ready_to_commit }}

runs:
  using: "composite"
  steps:
    - id: issue-parser
      uses: stefanbuck/github-issue-parser@v3
      with:
        template-path: ${{ inputs.template_path }}

    - name: Extract submission data
      id: issue-data
      shell: bash
      run: |
        standard_name=${{ steps.issue-parser.outputs.issueparser_name }}
        echo standard_name=$standard_name | tee -a "$GITHUB_ENV" "$GITHUB_OUTPUT"
        echo ready_to_commit=${{ contains(steps.issue-parser.outputs.issueparser_options, 'ready to commit') }} >> "$GITHUB_OUTPUT"
        echo '${{ steps.issue-parser.outputs.jsonString }}' > submission.json

    - name: Edit issue title
      id: issue-info
      shell: bash
      run: |
        issue_number=${{ github.event.issue.number }}
        echo issue_number=$issue_number >> "$GITHUB_OUTPUT"
        issue_title=$(gh issue view $issue_number --json title --jq '.title')
        if [ "$issue_title" == "${{ env.ISSUE_TITLE }}" ]; then
          gh issue edit "$issue_number" --title "${{ env.standard_name }}"
        fi
