name: Parse Artifacts
description: Parse JSON mapping of artifact names to paths

inputs:
  artifacts:
    description: 'JSON mapping of artifact names to paths, e.g. {"artifact1": "docs/section1"}'
    required: true

outputs:
  artifact_names:
    description: "Comma-separated list of artifact names"
    value: ${{ steps.parse.outputs.artifact_names }}
  artifact_paths:
    description: "Comma-separated list of artifact paths"
    value: ${{ steps.parse.outputs.artifact_paths }}

runs:
  using: "composite"
  steps:
    - id: parse
      shell: bash
      run: |
        # Parse artifacts input as JSON
        artifacts_json='${{ inputs.artifacts }}'
        names=()
        paths=()

        # Process JSON using jq
        for name in $(echo "$artifacts_json" | jq -r 'keys[]'); do
          path=$(echo "$artifacts_json" | jq -r --arg name "$name" '.[$name]')
          # Add to arrays
          names+=("$name")
          paths+=("$path")
        done

        # Convert arrays to comma-separated strings
        IFS=','
        artifact_names="${names[*]}"
        artifact_paths="${paths[*]}"

        # Set outputs
        echo "artifact_names=$artifact_names" >> $GITHUB_OUTPUT
        echo "artifact_paths=$artifact_paths" >> $GITHUB_OUTPUT

        # Echo artifact names and paths for debugging
        echo "Artifact Names: $artifact_names"
        echo "Artifact Paths: $artifact_paths"
