name: commit-issue
description: Commit valid Standard Name to branch.

inputs:
  standard-name:
    description: "The proposed Standard Name."
    required: true
  base-branch:
    description: "GitHub actions base branch."
    required: true
  topic-branch:
    description: "GitHub actions development branch."
    required: true
  issue-number:
    description: "GitHub issue number."
    required: true

runs:
  using: "composite"
  steps:

    - name: fetch topic branch
      shell: bash
      run: |
        git fetch origin ${{ inputs.topic-branch }}
        git switch ${{ inputs.topic-branch }}

    - name: download commit files from artifact
      uses: actions/download-artifact@v4
      with:
        name: issue-files-${{ inputs.issue-number }}
        path: ./

    - name: commit files to topic branch
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add standardnames.yml
        git add docs/img/${{ inputs.standard-name }}/
        # List all files that are staged for commit
        echo "Files added to git:"
        git diff --name-only --cached
        git commit -m "${{ inputs.standard-name }} Closes #${{ inputs.issue-number }} :rocket:"
        git push --set-upstream origin ${{ inputs.topic-branch }}
        git switch main  

    - name: run CI/CD workflow on topic-branch
      uses: actions/github-script@v7
      with:
        github-token: ${{ github.token }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'python-package.yml',
            ref: '${{ inputs.topic-branch }}',
          })

