name: IMAS Standard Name

on:
  issues:
    types: [edited, labeled]
  workflow_dispatch:

env:
  ISSUE_TITLE: "Standard Name Proposal"
  BASE_BRANCH: "develop"
  TOPIC_BRANCH: "submit"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ISSUE_URL: ${{ github.event.issue.html_url }}

jobs:
  imas-standard_name:
    if: contains(github.event.issue.labels.*.name, 'standard-name')
    runs-on: ubuntu-latest
    outputs:
      doc-ref: ${{ steps.document-issue.outputs.doc-ref }}
      valid-commit: ${{ steps.process-issue.outputs.valid-commit }}

    steps:
      - name: Comment on issue
        shell: bash
        if: ${{ ! contains(github.event.issue.labels.*.name, 'approve') }}
        env:
          update_message: ":construction: Automatic processing of this Standard Name proposal has been triggered. This process typically takes 30 seconds to complete."
        run: echo -e "$update_message" | gh issue comment $ISSUE_URL --body-file -

      - uses: actions/checkout@v4
        with:
          ref: main

      - id: parse-issue
        uses: ./.github/actions/parse-issue
        with:
          template_path: ".github/ISSUE_TEMPLATE/standard-name.yml"

      - uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install imas-standard-names
        run: |
          python -m pip install --upgrade pip
          pip install .

      - id: process-issue
        uses: ./.github/actions/process-issue
        with:
          standard-name: ${{ steps.parse-issue.outputs.standard-name }}
          overwrite-standard-name: ${{ steps.parse-issue.outputs.overwrite-standard-name }}
          ready-to-commit: ${{ steps.parse-issue.outputs.ready-to-commit }}

      - id: label-issue
        uses: ./.github/actions/label-issue
        with:
          standard-name: ${{ steps.parse-issue.outputs.standard-name }}
          duplicate-name: ${{ steps.process-issue.outputs.duplicate-name }}
          update-error: ${{ steps.process-issue.outputs.update-error }}

      - id: document-issue
        if: steps.process-issue.outputs.valid-commit == 'true'
        uses: ./.github/actions/document-standard-name
        with:
          doc-ref: issue-${{ steps.parse-issue.outputs.issue-number }}
          base-ref: ${{ env.BASE_BRANCH }}

      - id: commit-issue
        if: steps.process-issue.outputs.approved-valid-commit == 'true'
        uses: ./.github/actions/commit-issue
        with:
          standard-name: ${{ steps.parse-issue.outputs.standard-name }}
          base-branch: ${{ env.BASE_BRANCH }}
          topic-branch: ${{ env.TOPIC_BRANCH }}
          issue-number: ${{ steps.parse-issue.outputs.issue-number}}

      - id: raise-pull-request
        if: steps.process-issue.outputs.approved-valid-commit == 'true'
        uses: ./.github/actions/raise-pull-request
        with:
          base-branch: ${{ env.BASE_BRANCH }}
          topic-branch: ${{ env.TOPIC_BRANCH }}

  deploy-docs:
    permissions:
      contents: read
      pages: write
      id-token: write

    concurrency:
      group: "${{ github.workflow }}-${{ github.event.issue.number}}"
      cancel-in-progress: true

    if: ${{ needs.imas-standard_name.outputs.valid-commit == 'true' }}
    needs:
      - imas-standard_name

    runs-on: ubuntu-latest
    outputs:
      doc-url: ${{ steps.deploy-docs.outputs.page_url }}

    environment:
      name: github-pages
      url: ${{ steps.deploy-docs.outputs.page_url }}${{ needs.imas-standard_name.outputs.doc-ref }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - id: deploy-docs
        uses: ./.github/actions/deploy-docs
        with:
          artifacts: '{"${{ env.doc-ref }}": "${{ env.doc-ref }}"}'
        env:
          doc-ref: ${{ needs.imas-standard_name.outputs.doc-ref }}
