name: IMAS Standard Name

on:
  issues:
    types: [edited, labeled]
  workflow_dispatch:

env:
  ISSUE_TITLE: "Standard Name Proposal"
  BASE_BRANCH: "develop"
  TOPIC_BRANCH: "submit"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ISSUE_URL: ${{ github.event.issue.html_url }}

permissions:
  contents: write
  pages: write
  id-token: write
  issues: write
  pull-requests: write

concurrency:
  group: "issue-${{ github.event.issue.number }}"
  cancel-in-progress: true

jobs:
  check:
    if: contains(github.event.issue.labels.*.name, 'standard-name')
    runs-on: ubuntu-latest
    outputs:
      valid-commit: ${{ steps.process-issue.outputs.valid-commit }}
      approved-valid-commit: ${{ steps.process-issue.outputs.approved-valid-commit }}
      standard-name: ${{ steps.parse-issue.outputs.standard-name }}
      issue-number: ${{ steps.parse-issue.outputs.issue-number }}
      update-message: ${{ steps.process-issue.outputs.update-message }}

    steps:
      - name: Comment on issue
        shell: bash
        if: ${{ ! contains(github.event.issue.labels.*.name, 'approve') }}
        env:
          update_message: ":construction: Automatic processing of this Standard Name proposal has been triggered. This process typically takes 30 seconds to complete."
        run: echo -e "$update_message" | gh issue comment $ISSUE_URL --body-file -

      - uses: actions/checkout@v4
        with:
          ref: main

      - id: parse-issue
        uses: ./.github/actions/parse-issue
        with:
          template_path: ".github/ISSUE_TEMPLATE/standard-name.yml"

      - uses: ./.github/actions/install-project
        with:
          python-version: "3.12"

      - id: process-issue
        uses: ./.github/actions/process-issue
        with:
          standard-name: ${{ steps.parse-issue.outputs.standard-name }}
          overwrite-standard-name: ${{ steps.parse-issue.outputs.overwrite-standard-name }}
          ready-to-commit: ${{ steps.parse-issue.outputs.ready-to-commit }}

      - id: label-issue
        uses: ./.github/actions/label-issue
        with:
          standard-name: ${{ steps.parse-issue.outputs.standard-name }}
          duplicate-name: ${{ steps.process-issue.outputs.duplicate-name }}
          update-error: ${{ steps.process-issue.outputs.update-error }}

      - id: document-issue
        if: steps.process-issue.outputs.valid-commit == 'true'
        uses: ./.github/actions/document-standard-name
        with:
          doc-ref: issue-${{ steps.parse-issue.outputs.issue-number }}
          standard-names-file: submission.yml
          single-page: true

      - id: upload-commit-artifact
        if: steps.process-issue.outputs.approved-valid-commit == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: issue-files-${{ steps.parse-issue.outputs.issue-number }}
          path: |
            standardnames.yml
            docs/img/${{ steps.parse-issue.outputs.standard-name }}-[0-9]+\..*
          retention-days: 1

  deploy:
    needs:
      - check
    if: needs.check.outputs.valid-commit == 'true'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}/issues/issue-${{ needs.check.outputs.issue-number }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages

      - uses: actions/upload-pages-artifact@v3
        with:
          path: .
          retention-days: 1

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Comment on issue deployment
        if: ${{ ! contains(github.event.issue.labels.*.name, 'approve') }}
        shell: bash
        env:
          update_message: >

            ${{ needs.check.outputs.update-message }}

            Your Standard Name proposal has been published at [this link](
            ${{ steps.deployment.outputs.page_url }}/issues/issue-${{ needs.check.outputs.issue-number }}).
            Please verify that the information presented correctly reflects your intention.
            To make changes, click "Edit" from the three dots menu (⋯) in the top 
            right corner of this issue. Changes will automatically trigger an 
            update.


            > [!NOTE]\n
            > Assignees: Apply the "approve" label to approve this request.
            Application of the "approve" label will automatically commit changes to
            the submit branch and create or update the associated Pull Request.
        run: echo -e "$update_message" | gh issue comment $ISSUE_URL --body-file -

  commit:
    if: needs.check.outputs.approved-valid-commit == 'true'
    needs:
      - check
      - deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Check for PAT_TOKEN
        shell: bash
        run: |
          if [[ -z "${{ secrets.PAT_TOKEN }}" ]]; then
            echo "::error::PAT_TOKEN secret is not defined. Please add a personal access token with repo and workflow scopes to your repository secrets."
            exit 1
          fi

      - id: commit-issue
        uses: ./.github/actions/commit-issue
        with:
          standard-name: ${{ needs.check.outputs.standard-name }}
          base-branch: ${{ env.BASE_BRANCH }}
          topic-branch: ${{ env.TOPIC_BRANCH }}
          issue-number: ${{ needs.check.outputs.issue-number }}
          pat-token: ${{ secrets.PAT_TOKEN }}

      - id: raise-pull-request
        uses: ./.github/actions/raise-pull-request
        with:
          base-branch: ${{ env.BASE_BRANCH }}
          topic-branch: ${{ env.TOPIC_BRANCH }}
          pat-token: ${{ secrets.PAT_TOKEN }}
