on:
  workflow_call:
    outputs:
      standard-name:
        description: 'Proposed Standard Name.'
        value: ${{ jobs.parse-issue.outputs.standard-name }}
      submission:
        description: 'Submission JSON string.'
        value: ${{ jobs.parse-issue.outputs.submission }}
      options:
        description: 'Issue checkbox options.'
        value: ${{ jobs.parse-issue.outputs.options }}


jobs:
  parse-issue:
    runs-on: ubuntu-latest
    outputs:
      standard-name: ${{ steps.issue-parser.outputs.issueparser_name }}
      submission: ${{ steps.issue-parser.outputs.jsonString }}
      options: ${{ steps.issue-parser.outputs.issueparser_options }}
    
    steps:
    - uses: actions/checkout@v3
    - uses: stefanbuck/github-issue-parser@v3
      id: issue-parser
      with:
        template-path: .github/ISSUE_TEMPLATE/standard-name.yml

    - name: echo outputs
      run: |
        echo standard-name='${{ steps.issue-parser.outputs.issueparser_name }}'
        echo submission='${{ steps.issue-parser.outputs.jsonString }}'
        echo options='${{ steps.issue-parser.outputs.issueparser_options }}'
